USE [CarSales_DW]
GO

/****** Object:  Table [dbo].[DimCarMake]    Script Date: 5/15/2026 8:18:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DimCarMake](
	[CarMakeSK] [int] IDENTITY(1,1) NOT NULL,
	[CarMake] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[CarMakeSK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


